function [VarMODIS] = Parameters_MODIS_Data_Dynamic(resampling)
varid                           =   0;

%% 5600,
varid                           =   varid +1;
VarMODIS(varid).Productnames    =   'MCD43C3'; 
VarMODIS(varid).name            =   'Albedo';  
VarMODIS(varid).Varname        	=   'BSA';  
VarMODIS(varid).Dirnames        =   'MOTA';  
VarMODIS(varid).Versionnames    =   '.005'; 
VarMODIS(varid).Grid            =   'CMG';
VarMODIS(varid).acquisition     =   'Static';
VarMODIS(varid).Frequency       =   8;
VarMODIS(varid).resampling      =   resampling;
VarMODIS(varid).IdSDS           =   10;

varid                           =   varid +1;
VarMODIS(varid).Productnames    =   'MCD43C3'; 
VarMODIS(varid).name            =   'Albedo';
VarMODIS(varid).Varname         =   'WSA';
VarMODIS(varid).Dirnames        =   'MOTA';  
VarMODIS(varid).Versionnames    =   '.005'; 
VarMODIS(varid).Grid            =   'CMG';
VarMODIS(varid).acquisition     =   'Static';
VarMODIS(varid).Frequency       =   8;
VarMODIS(varid).resampling      =   resampling;
VarMODIS(varid).IdSDS           =   20;

varid                           =   varid +1;
VarMODIS(varid).Productnames   	=   'MOD13C1'; 
VarMODIS(varid).name            =   'NDVI';
VarMODIS(varid).Varname        	=   'NDVI';  
VarMODIS(varid).Dirnames        =   'MOLT';  
VarMODIS(varid).Versionnames    =   '.005'; 
VarMODIS(varid).Grid            =   'CMG';
VarMODIS(varid).acquisition     =   'Static';
VarMODIS(varid).Frequency       =   8;
VarMODIS(varid).resampling      =   resampling;
VarMODIS(varid).IdSDS           =   01;

varid                           =   varid +1;
VarMODIS(varid).Productnames   	=   'MOD11C1'; 
VarMODIS(varid).name            =   'LST';
VarMODIS(varid).Varname        	=   'LST';  
VarMODIS(varid).Dirnames        =   'MOLT';  
VarMODIS(varid).Versionnames    =   '.005'; 
VarMODIS(varid).Grid            =   'CMG';
VarMODIS(varid).acquisition     =   'Static';
VarMODIS(varid).Frequency       =   1;
VarMODIS(varid).resampling      =   resampling;
VarMODIS(varid).IdSDS           =   1;

varid                           =   varid +1;
VarMODIS(varid).Productnames   	=   'MOD11C1'; 
VarMODIS(varid).name            =   'LST';
VarMODIS(varid).Varname        	=   'time';  
VarMODIS(varid).Dirnames        =   'MOLT';  
VarMODIS(varid).Versionnames    =   '.005'; 
VarMODIS(varid).Grid            =   'CMG';
VarMODIS(varid).acquisition     =   'Static';
VarMODIS(varid).Frequency       =   1;
VarMODIS(varid).resampling      =   resampling;
VarMODIS(varid).IdSDS           =   3;

varid                           =   varid +1;
VarMODIS(varid).Productnames   	=   'MOD11C1'; 
VarMODIS(varid).name            =   'LST';
VarMODIS(varid).Varname        	=   'theta_v';  
VarMODIS(varid).Dirnames        =   'MOLT';  
VarMODIS(varid).Versionnames    =   '.005'; 
VarMODIS(varid).Grid            =   'CMG';
VarMODIS(varid).acquisition     =   'Static';
VarMODIS(varid).Frequency       =   1;
VarMODIS(varid).resampling      =   resampling;
VarMODIS(varid).IdSDS           =   3;

varid                           =   varid +1;
VarMODIS(varid).Productnames   	=   'MOD11C1'; 
VarMODIS(varid).name            =   'LST';
VarMODIS(varid).Varname        	=   'Emissivity_29';  
VarMODIS(varid).Dirnames        =   'MOLT';  
VarMODIS(varid).Versionnames    =   '.005'; 
VarMODIS(varid).Grid            =   'CMG';
VarMODIS(varid).acquisition     =   'Static';
VarMODIS(varid).Frequency       =   1;
VarMODIS(varid).resampling      =   resampling;
VarMODIS(varid).IdSDS           =   12;

varid                           =   varid +1;
VarMODIS(varid).Productnames   	=   'MOD11C1'; 
VarMODIS(varid).name            =   'LST';
VarMODIS(varid).Varname        	=   'Emissivity_31';  
VarMODIS(varid).Dirnames        =   'MOLT';  
VarMODIS(varid).Versionnames    =   '.005'; 
VarMODIS(varid).Grid            =   'CMG';
VarMODIS(varid).acquisition     =   'Static';
VarMODIS(varid).Frequency       =   1;
VarMODIS(varid).resampling      =   resampling;
VarMODIS(varid).IdSDS           =   13;

varid                           =   varid +1;
VarMODIS(varid).Productnames   	=   'MOD11C1'; 
VarMODIS(varid).name            =   'LST';
VarMODIS(varid).Varname        	=   'Emissivity_32';  
VarMODIS(varid).Dirnames        =   'MOLT';  
VarMODIS(varid).Versionnames    =   '.005'; 
VarMODIS(varid).Grid            =   'CMG';
VarMODIS(varid).acquisition     =   'Static';
VarMODIS(varid).Frequency       =   1;
VarMODIS(varid).resampling      =   resampling;
VarMODIS(varid).IdSDS           =   14;
