function [Edaily,E0daily, Rndaily, Rn,G0,H,LE,LE0] =   SEBS(LAI,fc, hc, Albedo, Emissivity, LST_K,                    	...
                                                                 Zref, Zref10, Hpbl,                                        ...
                                                                 Tref_K,qaref, Pref_Pa,Ps_Pa,P0_Pa, Uref10,                 ...
                                                                 SWd,  LWd, SWd24,                                          ...
                                                                 day_angle, lat_rad, Ta_av_K,Ns)
    %% KB-1
    [z0m, d0, z0h]                                  	=  SEBS_kb_1(   LAI, fc, hc,                    ...
                                                                        Zref, Zref10,                   ...
                                                                        Tref_K,qaref, Pref_Pa,Ps_Pa,P0_Pa, Uref10);
    
    %% Energy Balance calculations
    [Rn, G0, H, LE, LE0, EF,EF0]                        =   SEBS_EnergyBalance(d0, z0m, z0h,                                    ...
                                                                                LAI,fc, hc, Albedo, Emissivity, LST_K,          ...
                                                                                Zref, Zref10, Hpbl,                             ...
                                                                                Tref_K,qaref, Pref_Pa,Ps_Pa,P0_Pa, Uref10,      ...
                                                                                SWd, LWd);

    %% Daily evapotranspiration
    [Rndaily,Edaily,E0daily]                            =   SEBS_Daily_Evapotranspiration(EF, EF0, Albedo, SWd24, Ta_av_K, Ns, day_angle, lat_rad);
    
return